export const ADD_FOLDER = "ADD_FOLDER";
export const ADD_FOLDER_SUCCESS = "ADD_FOLDER_SUCCESS";
export const FOLDER_ERROR = "FOLDER_ERROR";
export const ADD_ALL_FOLDER = "ADD_ALL_FOLDER";
export const ADD_ALL_FOLDERS_SUCCESS = "ADD_ALL_FOLDERS_SUCCESS";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const DELETE_FOLDER_SUCCESS = "DELETE_FOLDER_SUCCESS";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS= "ADD_TASK_SUCCESS";
export const LOAD_TASK = "LOAD_TASK";
export const LOAD_TASK_SUCCESS = "LOAD_TASK_SUCCESS";
export const TASK_ERROR = "TASK_ERROR";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const REGISTER = "REGISTER";

export const AUTHENTICATE_TOAPI = "AUTHENTICATE_TOAPI";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_ERROR = "AUTHENTICATE_ERROR";
export const AUTHENTICATE = "AUTHENIICATE";

export const LOGOUT = "LOGOUT";

export const LOADING_START = "LOADING_START";
export const LOADING_FINISH = "LOADING_FINISH";

export const MODAL_OPEN = "MODAL_OPEN";
export const CLOSE_ALERT ="CLOSE_ALERT";
